name: npm-publish
on:
  push:
    branches:
      - main 
jobs:
  npm-publish:
    name: Publish to Github Packages
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Release')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.0.0
    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: Publish package
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: publish
        registry-url: npm.pkg.github.com
        auth-token: ${{ secrets.GITHUB_TOKEN }}

  # https://github.community/t5/GitHub-Actions/Workflow-is-failing-if-no-job-can-be-ran-due-to-condition/m-p/38186#M3250
  always_job:
    name: Aways run job
    runs-on: ubuntu-latest
    steps:
      - name: Always run
        run: echo "This job is used to prevent the workflow to fail when all other jobs are skipped."
